sudo: false
language: node_js
node_js:
  - v6
  - v5
  - v4
addons:
  code_climate:
    repo_token: 38bcbb51ebcbe80f1181ffe908a2549f76f91552f2f9a94a2cde548fbae24ba1
after_script:
  - npm install codeclimate-test-reporter
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
